!!com.example.forkliftrestserver.model.SemaphoreList
semaphores:
  - id: 2
    quad:
      npoints: 4
      xpoints: [0, 0, 10, 10]
      ypoints: [0, 10, 10, 0]
  - id: 5
    quad:
      npoints: 4
      xpoints: [ 100, 100, 110, 110 ]
      ypoints: [ 100, 110, 110, 100 ]
