!!com.example.forkliftrestserver.model.RegionList
regions:
  - area:
      points:
        - {x: 50, y: 50}
        - {x: 50, y: 55}
        - {x: 55, y: 55}
        - {x: 55, y: 50}
    forkliftSerialNumber: -1
    id: 10
  - area:
      points:
        - {x: 20, y: 20}
        - {x: 20, y: 25}
        - {x: 25, y: 25}
        - {x: 25, y: 20}
    forkliftSerialNumber: -1
    id: 5
